export const skillsData = [
  { name: "REACT", value: 90 },
  { name: "NODE", value: 90 },
  { name: "JAVASCRIPT", value: 80 },
  { name: "TYPESCRIPT", value: 80 },
  { name: "MYSQL", value: 75 },
  { name: "AWS", value: 75 },
  { name: "CSS", value: 85 },
  { name: "HTML", value: 85 },
  { name: "JEST", value: 80 },
  { name: "ENZYME", value: 80 },
  { name: "CHAI", value: 80 },
  { name: "MOCHA", value: 80 },
  { name: "MONGODB", value: 85 },
  { name: "POSTGRESQL", value: 85 },
  { name: "REACT NATIVE", value: 75 },
  { name: "SWAGGER", value: 85 },
  { name: "EXPRESS", value: 90 },
];
